# name: CI
# on: push

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: yarn
#       - run: yarn test
name: CI
on:
  pull_request:
      branches:
          - master
          - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
