name: CI
on:
  pull_request:
      branches:
          - master
          - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
